---
editor: visual
---

# Pacotes usados para rodar os progamas para visualizar a produtividade o peso de mil grãos e desfolha do trabalho

```{r, warning=FALSE, message=FALSE}

library(tidyverse)
library(gsheet)
library(patchwork)
library(ggplot2)
library(ggthemes)
library(performance)
library(emmeans)
library(multcomp)
library(multcompView)
library(MASS)
library(DHARMa)



```

# Testes estatísticos e análises da produtividade peso de mil grãos e desfolha

```{r warning=FALSE, message=FALSE}

prod <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1D_tSkv6calLSIxxzwG_qiMH3cBlG1Y0B/edit?gid=123849322#gid=123849322")

aov_prod <- lm(`Produtividade (kg/ha)` ~ Tratamentos + Blocos,
               data = prod)

anova(aov_prod)
check_normality(aov_prod)
check_heteroscedasticity(aov_prod)
summary(aov_prod)
medias_prod <- emmeans(aov_prod, ~ Tratamentos)
pwpm(medias_prod)
cld(medias_prod, Letters = LETTERS)


aov_des <- lm(`Desfolha (%)` ~ Tratamentos + Blocos,
               data = prod)

anova(aov_des)
check_normality(aov_des)
check_heteroscedasticity(aov_des)
summary(aov_des)
medias_des <- emmeans(aov_des, ~ Tratamentos)
pwpm(medias_des)
cld(medias_des, Letters = LETTERS)


aov_peso <- lm(`PMG (g)` ~ Tratamentos + Blocos,
               data = prod)

anova(aov_peso)
check_normality(aov_peso)
check_heteroscedasticity(aov_peso)
summary(aov_peso)
medias_peso <- emmeans(aov_peso, ~ Tratamentos)
pwpm(medias_peso)
cld(medias_peso, Letters = LETTERS)





```

# Gráficos para visualizar a interação entre produtividade peso de mil grãos e desfolha

```{r warning=FALSE, message=FALSE}

prod |>
  ggplot(aes(Tratamentos, `Produtividade (kg/ha)`,
             fill = Tratamentos))+
  geom_col()

prod |>
  ggplot(aes(Tratamentos, `Desfolha (%)`,
             fill = Tratamentos))+
  geom_col()

prod |>
  ggplot(aes(Tratamentos, `PMG (g)`,
             fill = Tratamentos))+
  geom_col()



prod |>
  ggplot(aes(`Produtividade (kg/ha)`, `Desfolha (%)`,
             color = Tratamentos))+
    geom_point()

prod |>
  ggplot(aes(`PMG (g)`, `Desfolha (%)`,
             color = Tratamentos))+
    geom_point()

prod |>
  ggplot(aes(`PMG (g)`, `Produtividade (kg/ha)`,
             color = Tratamentos))+
    geom_point()




```
